#!/bin/bash

echo "Faking that data..."

curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/borat", "title": "borat", "stataus": "pass", "message": "Build Successful"} }'

echo "Done!"