#!/bin/bash

function help () {
	echo "Dashr - Jamesford makes a shell script. You've been warned."
	echo ""
	echo "	dashr help      - displays this help text"
	echo "	dashr create    - replicates databases"
	echo "	dashr reset     - clears non-default databases"
	echo "	dashr start     - runs npm install and then starts up"
	echo "	dashr install   - updates gems, installs compass (gem), installs grunt-cli (npm)"
}

if [ $1 ]
then
	case "$1" in
		create)
			# echo "Create command"
			echo "Adding databases..."
curl --silent -H 'Content-Type: application/json' -X POST http://localhost:5984/_replicate -d ' {"source": "http://192.168.1.14:5984/dashboard_widgets", "target": "dashboard_widgets", "create_target":true} '
curl --silent -H 'Content-Type: application/json' -X POST http://localhost:5984/_replicate -d ' {"source": "http://192.168.1.14:5984/dashboard_githubrepos", "target": "dashboard_githubrepos", "create_target":true} '
curl --silent -H 'Content-Type: application/json' -X POST http://localhost:5984/_replicate -d ' {"source": "http://192.168.1.14:5984/dashboard_countdown", "target": "dashboard_countdown", "create_target":true} '
			echo "Done!"
		;;

		reset)
			# echo "Reset command"
			echo "Clearing dashr databases..."
			Widgets=$(curl --silent -X DELETE http://localhost:5984/dashboard_widgets)
			ghrepos=$(curl --silent -X DELETE http://localhost:5984/dashboard_githubrepos)
			count=$(curl --silent -X DELETE http://localhost:5984/dashboard_countdown)

			if [ "$Widgets" = '{"ok":true}' ]
			then
				echo "Widgets database removed!"
			elif [ "$Widgets" = '{"error":"not_found","reason":"missing"}' ] 
			then
				echo "Widgets database doesn't exist"
			else
				echo "Failed :("
			fi

			if [ "$ghrepos" = '{"ok":true}' ]
			then
				echo "Githubrepos database removed!"
			elif [ "$ghrepos" = '{"error":"not_found","reason":"missing"}' ] 
			then
				echo "Githubrepos database doesn't exist"
			else
				echo "Failed :("
			fi

			if [ "$count" = '{"ok":true}' ]
			then
				echo "Countdown database removed!"
			elif [ "$count" = '{"error":"not_found","reason":"missing"}' ] 
			then
				echo "Countdown database doesn't exist"
			else
				echo "Failed :("
			fi
		;;

		start)
			echo "Installing dependencies..."
			npm install
			echo "Starting processes..."
			grunt
		;;

		install)
			gem update
			gem install compass
			npm install -g grunt-cli
		;;

		help)
			help
		;;

		*)
			# echo "Typed nothing :("
			echo "Not a valid dashr command"
			echo "Type 'dashr help' for a list of commands"
		;;
	esac
else
	help
fi
