name: Dashy
description: A sample web application
dependencies:
  angular: any
  browser: any
  di: any
  http: any
  http_server: any
  redis_client: any
  uuid: any
  yaml: any
  args: any
  route: ">=0.4.0 <0.5.0"
