name: dashy
description: An awesome dashboard application
dependencies:
  angular:
    git:
      url: git://github.com/angular/angular.dart.git
  browser: any
  yaml: any
  d3: any
  markdown: any
  html5_dnd: any
dev_dependencies:
  unittest: '>=0.10.1 <0.12.0'
  mock: '>=0.10.0 <0.12.0'
  guinness: '>=0.1.1 <0.2.0'


transformers:
- angular
