name: dashy
description: An awesome dashboard application
dependencies:
  angular:
    git:
      url: git://github.com/angular/angular.dart.git
  browser: any
  unittest: any
  yaml: any
  d3: any

transformers:
- angular
