#!/bin/bash

echo "Setting up CouchDB for Dashy..."

echo "Adding Databases..."
curl -X PUT http://127.0.0.1:5984/widgets
curl -X PUT http://127.0.0.1:5984/sources
curl -X PUT http://127.0.0.1:5984/builds
curl -X PUT http://127.0.0.1:5984/commits
curl -X PUT http://127.0.0.1:5984/pictures
curl -X PUT http://127.0.0.1:5984/githubrepos
curl -X PUT http://127.0.0.1:5984/internet
echo "Databases added."

echo "Posting database views..."
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{"_id": "_design/widgets","language": "javascript","views": {"all": {"map": "function (doc) {if (doc.content && doc.config && doc.layout) {emit(doc._rev,{'content' :doc.content,'config' : doc.config,'layout' : doc.layout});}}"}}}'
curl -X POST http://127.0.0.1:5984/sources -H "Content-Type: application/json" -d '{"_id": "_design/sources","language": "javascript","views": {"all": {"map": "function (doc) {if (doc.name) {emit(doc._rev,{'name' :doc.name});}}"}}}'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{"_id": "_design/source","language": "javascript","views": {"all": {"map": "function (doc) {if (doc.time && doc.data) {emit(doc._rev,{'time' : doc.time,'data' : doc.data});}}"}}}'
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{"_id": "_design/source","language": "javascript","views": {"all": {"map": "function (doc) {if (doc.time && doc.data) {emit(doc._rev,{'time' : doc.time,'data' : doc.data});}}"}}}'
curl -X POST http://127.0.0.1:5984/pictures -H "Content-Type: application/json" -d '{"_id": "_design/source","language": "javascript","views": {"all": {"map": "function (doc) {if (doc.time && doc.data) {emit(doc._rev,{'time' : doc.time,'data' : doc.data});}}"}}}'
curl -X POST http://127.0.0.1:5984/githubrepos -H "Content-Type: application/json" -d '{"_id": "_design/source","language": "javascript","views": {"all": {"map": "function (doc) {if (doc.time && doc.data) {emit(doc._rev,{'time' : doc.time,'data' : doc.data});}}"}}}'
curl -X POST http://127.0.0.1:5984/internet -H "Content-Type: application/json" -d '{"_id": "_design/source","language": "javascript","views": {"all": {"map": "function (doc) {if (doc.time && doc.data) {emit(doc._rev,{'time' : doc.time,'data' : doc.data});}}"}}}'
echo "Views complete."

echo "Posting Widget Data..."
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "Announcements"
   },
   "content": [
       {
           "template": "markdown",
           "refresh": 0,
           "options": {
               "markdown": "# Hello World!"
           }
       },
       {
           "template": "countdown",
           "refresh": 0,
           "options": {
               "enddate": "2014-03-15"
           }
       }
   ],
   "layout": {
       "row": 1,
       "column": 3,
       "width": 4,
       "height": 2
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "Builds"
   },
   "content": [
       {
           "template": "list",
           "source": "builds",
           "refresh": 5000,
           "options": {
           }
       }
   ],
   "layout": {
       "row": 1,
       "column": 1,
       "width": 2,
       "height": 6
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "GitHub Commits"
   },
   "content": [
       {
           "template": "list",
           "source": "commits",
           "refresh": 5000,
           "options": {
           }
       }
   ],
   "layout": {
       "row": 3,
       "column": 3,
       "width": 2,
       "height": 4
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "internet speed"
   },
   "content": [
       {
           "template": "gauge",
           "source": "internet",
           "refresh": 2000,
           "options": {
               "max": 800,
               "min": 0
           }
       }
   ],
   "layout": {
       "row": 5,
       "column": 5,
       "width": 2,
       "height": 2
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "Latest Pic"
   },
   "content": [
       {
           "template": "picture",
           "source": "pictures",
           "refresh": 5000,
           "options": {
           }
       }
   ],
   "layout": {
       "row": 3,
       "column": 5,
       "width": 2,
       "height": 2
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "wiredcraft values"
   },
   "content": [
       {
           "template": "sum",
           "source": "githubrepos",
           "refresh": 5000,
           "options": {
               "prepend": "",
               "append": "K",
               "subtitle": "visitors"
           }
       },
       {
           "template": "delta",
           "source": "githubrepos",
           "refresh": 5000,
           "options": {
           }
       }
   ],
   "layout": {
       "row": 1,
       "column": 11,
       "width": 2,
       "height": 2
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "devo.ps values"
   },
   "content": [
       {
           "template": "sum",
           "source": "githubrepos",
           "refresh": 5000,
           "options": {
               "prepend": "",
               "append": "K",
               "subtitle": "visitors"
           }
       },
       {
           "template": "delta",
           "source": "githubrepos",
           "refresh": 5000,
           "options": {
           }
       }
   ],
   "layout": {
       "row": 3,
       "column": 11,
       "width": 2,
       "height": 2
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "MailChimp Values"
   },
   "content": [
       {
           "template": "sum",
           "source": "githubrepos",
           "refresh": 5000,
           "options": {
               "prepend": "",
               "append": "K",
               "subtitle": "visitors"
           }
       },
       {
           "template": "delta",
           "source": "githubrepos",
           "refresh": 5000,
           "options": {
           }
       }
   ],
   "layout": {
       "row": 5,
       "column": 11,
       "width": 2,
       "height": 2
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "Wiredcraft Metrics"
   },
   "content": [
       {
           "template": "linechart",
           "options": {
               "points": 7
           },
           "refresh": 2000,
           "source": "githubrepos"
       }
   ],
   "layout": {
       "row": 1,
       "column": 7,
       "height": 2,
       "width": 4
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "devo.ps metrics"
   },
   "content": [
       {
           "template": "linechart",
           "source": "githubrepos",
           "refresh": 5000,
           "options": {
               "points": 7
           }
       }
   ],
   "layout": {
       "row": 3,
       "column": 7,
       "width": 4,
       "height": 2
   }
}'
curl -X POST http://127.0.0.1:5984/widgets -H "Content-Type: application/json" -d '{
   "config": {
       "title": "MailChimp Stats"
   },
   "content": [
       {
           "template": "linechart",
           "options": {
               "points": 7
           },
           "source": "githubrepos",
           "refresh": 5000
       }
   ],
   "layout": {
       "row": 5,
       "column": 7,
       "width": 4,
       "height": 2
   }
}'


echo "Widget Data Complete."

echo "Posting Sources Data..."
curl -X POST http://127.0.0.1:5984/sources -H "Content-Type: application/json" -d '{ "_id":"builds", "name": "builds" }'
curl -X POST http://127.0.0.1:5984/sources -H "Content-Type: application/json" -d '{ "_id":"commits", "name": "commits" }'
curl -X POST http://127.0.0.1:5984/sources -H "Content-Type: application/json" -d '{ "_id":"githubrepos", "name": "githubrepos" }'
curl -X POST http://127.0.0.1:5984/sources -H "Content-Type: application/json" -d '{ "_id":"pictures", "name": "pictures" }'
echo "Sources Complete."

echo "Posting Builds Data..."
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/borat", "title": "borat", "status": "pass", "message": "Build Successful"} }'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/dashy", "title": "dashy", "status": "pass", "message": "Build Successful"} }'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/embarq", "title": "Embarq", "status": "fail", "message": "Build Failed"} }'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/devo.ps", "title": "devo.ps", "status": "pass", "message": "Build Successful"} }'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/moleskin", "title": "Moleskin", "status": "fail", "message": "Build Failed"} }'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/shanghaios.org", "title": "ShanghaiOS.org", "status": "pass", "message": "Build Successful"} }'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/wiredcraft.com", "title": "wiredcraft.com", "status": "fail", "message": "Build Failed"} }'
curl -X POST http://127.0.0.1:5984/builds -H "Content-Type: application/json" -d '{ "time": "1234567890", "data": {"repository": "http://github.com/wiredcraft/AppNap", "title": "AppNap", "status": "pass", "message": "Build Successful"} }'
echo "Builds Complete."

echo "Posting Commits Data..."
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{ "time": "2013-05-14T21:34:49Z", "data": {"user": "Jamesford", "title": "Super Commit!", "image": "https://secure.gravatar.com/avatar/cfdfd092fdad6be1a2d80bdbea98d9ead=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"} }'
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{ "time": "2013-06-14T09:34:49Z", "data": {"user": "Jamesford", "title": "Test Commit", "image": "https://secure.gravatar.com/avatar/cfdfd092fdad6be1a2d80bdbea98d9ead=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"} }'
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{ "time": "2013-04-14T21:34:49Z", "data": {"user": "Jamesford", "title": "Awesome Commit", "image": "https://secure.gravatar.com/avatar/cfdfd092fdad6be1a2d80bdbea98d9ead=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"} }'
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{ "time": "2013-02-27T04:02:33Z", "data": {"user": "frankdou", "title": "Franks Commit!", "image": "https://secure.gravatar.com/avatar/26c5aee074ac63ffff6b37ee8892ea33?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"} }'
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{ "time": "2013-07-12T07:22:20Z", "data": {"user": "frankdou", "title": "Recent Commit", "image": "https://secure.gravatar.com/avatar/26c5aee074ac63ffff6b37ee8892ea33?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"} }'
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{ "time": "2012-12-04T19:21:59Z", "data": {"user": "Borat", "title": "Borat Too, Vanilla face", "image": "https://secure.gravatar.com/avatar/18a9f462bd7774941b521c8bc071fe24?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"} }'
curl -X POST http://127.0.0.1:5984/commits -H "Content-Type: application/json" -d '{ "time": "2012-11-30T11:11:11Z", "data": {"user": "Sterling Archer", "title": "Dangerzone!!", "image": "https://secure.gravatar.com/avatar/a777586ddf06117bf63b2b77e12eae89?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"} }'
echo "Commits Complete."

echo "Posting Pictures Data..."
curl -X POST http://127.0.0.1:5984/pictures -H "Content-Type: application/json" -d '{ "time": "2013-06-14T09:34:49Z", "data": {"title": "A Cool Pic", "image": "http://img.timeinc.net/time/daily/2007/0701/360_borat_lebanon0109.jpg"} }'
curl -X POST http://127.0.0.1:5984/pictures -H "Content-Type: application/json" -d '{ "time": "2013-06-15T07:49:35Z", "data": {"title": "Borat", "image": "http://www.film.com/wp-content/uploads/2012/05/Sacha-Baron-Cohen-borat-django-unchained-tarantino.png"} }'
echo "Pictures Complete."

echo "Posting Internet Data..."
curl -X POST http://127.0.0.1:5984/internet -H "Content-Type: application/json" -d '{ "time": "2013-06-14T09:34:49Z", "data": {"value": 476} }'
curl -X POST http://127.0.0.1:5984/internet -H "Content-Type: application/json" -d '{ "time": "2013-06-14T09:34:49Z", "data": {"value": 345} }'
curl -X POST http://127.0.0.1:5984/internet -H "Content-Type: application/json" -d '{ "time": "2013-06-14T09:34:49Z", "data": {"value": 688} }'

echo "Internet Complete."

echo "Executing Nodejs script for githubrepos data..."
node install/githubreposData.js || nodejs install/githubreposData.js
echo "githubrepos Complete."

echo "================================"
echo "CouchDB has been setup for Dashy!"